#!/usr/bin/env python3
"""
Generate an HTML comparison report between original and corrected assemblies.
"""
import sys
import argparse
import os

def parse_stats_file(stats_file):
    """Parse assembly stats file into dictionary."""
    stats = {}
    if not os.path.exists(stats_file):
        return stats
    with open(stats_file) as f:
        for line in f:
            line = line.strip()
            if ':' in line and not line.startswith('='):
                key, value = line.split(':', 1)
                stats[key.strip()] = value.strip()
    return stats

def generate_comparison_html(original_stats, corrected_stats, sample_name, output_file):
    """Generate side-by-side comparison HTML."""
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Assembly Comparison Report – {sample_name}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        h1 {{ color: #2c3e50; }}
        .comparison {{ display: flex; gap: 20px; margin: 20px 0; }}
        .column {{ flex: 1; padding: 15px; border-radius: 8px; }}
        .original {{ background: #fdecea; }}
        .corrected {{ background: #e8f5e9; }}
        table {{ width: 100%; border-collapse: collapse; margin: 10px 0; }}
        th, td {{ padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background: #3498db; color: white; }}
        .improvement {{ color: #27ae60; font-weight: bold; }}
        .summary {{ background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }}
    </style>
</head>
<body>
    <h1>Assembly Comparison: Original vs Corrected</h1>
    <h2>Sample: {sample_name}</h2>

    <div class="summary">
        <p>This report compares the original 3D-DNA assembly with the manually reviewed and corrected version using Juicebox.</p>
        <p><strong>Review date:</strong> Generated by post-review pipeline</p>
    </div>

    <div class="comparison">
        <div class="column original">
            <h3>Original Assembly</h3>
            <table>
                TABLE_ORIGINAL
            </table>
        </div>
        <div class="column corrected">
            <h3>Corrected Assembly</h3>
            <table>
                TABLE_CORRECTED
            </table>
        </div>
    </div>

    <h3>Key Metrics Comparison</h3>
    <table>
        <tr><th>Metric</th><th>Original</th><th>Corrected</th><th>Change</th></tr>
        COMPARISON_ROWS
    </table>

    <p><em>Manual review performed using Juicebox GUI. Corrected assembly generated via 3D-DNA post-review pipeline.</em></p>
</body>
</html>"""

    table_original = ""
    for key, value in original_stats.items():
        table_original += f"<tr><td>{key}</td><td>{value}</td></tr>\n"

    table_corrected = ""
    for key, value in corrected_stats.items():
        table_corrected += f"<tr><td>{key}</td><td>{value}</td></tr>\n"

    # Compare key metrics
    key_metrics = ['Total length', 'Number of contigs', 'N50', 'L50', 'N90', 'L90']
    comparison_rows = ""
    for metric in key_metrics:
        orig = original_stats.get(metric, 'N/A')
        corr = corrected_stats.get(metric, 'N/A')
        change = ""
        if 'N/A' not in [orig, corr]:
            try:
                orig_val = float(orig.replace(',', '').replace('bp', '').strip())
                corr_val = float(corr.replace(',', '').replace('bp', '').strip())
                if orig_val > 0:
                    pct = (corr_val - orig_val) / orig_val * 100
                    change = f'<span class="improvement">{pct:+.1f}%</span>'
                else:
                    change = 'N/A'
            except ValueError:
                change = 'N/A'
        comparison_rows += f"<tr><td>{metric}</td><td>{orig}</td><td>{corr}</td><td>{change}</td></tr>\n"

    html = html.replace('TABLE_ORIGINAL', table_original)
    html = html.replace('TABLE_CORRECTED', table_corrected)
    html = html.replace('COMPARISON_ROWS', comparison_rows)
    html = html.replace('{sample_name}', sample_name)

    with open(output_file, 'w') as f:
        f.write(html)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--original-stats', default='')
    parser.add_argument('--corrected-stats', required=True)
    parser.add_argument('--corrected-quast', default='')
    parser.add_argument('--output', required=True)
    parser.add_argument('--sample', default='unknown')
    args = parser.parse_args()

    original_stats = parse_stats_file(args.original_stats)
    corrected_stats = parse_stats_file(args.corrected_stats)

    if not corrected_stats:
        with open(args.output, 'w') as f:
            f.write("<html><body><p>No corrected stats available.</p></body></html>")
        return

    generate_comparison_html(original_stats, corrected_stats, args.sample, args.output)
    print(f"Comparison report written to {args.output}", file=sys.stderr)

if __name__ == '__main__':
    main()
